// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT Test1

lv_obj_t * ui_Test1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Test1;
    cui_Test1 = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_Test1, 100);
    lv_obj_set_height(cui_Test1, 50);
    lv_obj_set_x(cui_Test1, -83);
    lv_obj_set_y(cui_Test1, -58);
    lv_obj_set_align(cui_Test1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Test1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_TEST1_NUM);
    children[UI_COMP_TEST1_TEST1] = cui_Test1;
    lv_obj_add_event_cb(cui_Test1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Test1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Test1_create_hook(cui_Test1);
    return cui_Test1;
}

