long int dis;
long int tim = millis();
char valstring1[20];
char valstring2[20];
char valstring3[20];
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Density;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Moisture;
lv_obj_t * ui_MoistArc;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Temp;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Button2;
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label6;
lv_obj_t * ui____initial_actions0;
